services:
  extractor:
    build:
      context: .
      dockerfile: extractor/Dockerfile
    volumes:
      - ./data-extractor:/data
    environment:
      - KBC_DATADIR=/data

  writer:
    build:
      context: .
      dockerfile: writer/Dockerfile
    volumes:
      - ./data-writer:/data
    environment:
      - KBC_DATADIR=/data
