[project]
name = "acumatica-extractor"
version = "0.0.0"
readme = "README.md"
requires-python = "~=3.13.0"
dependencies = [
    "freezegun>=1.5.1",
    "keboola-component>=1.6.10",
    "keboola-http-client>=1.0.1",
    "keboola-utils>=1.1.0",
    "mock>=5.2.0",
    "pydantic>=2.11.3",
    "requests>=2.32.0",
    "shared",
]

[dependency-groups]
dev = [
    "keboola-datadirtest>=2.1.1",
    "pre-commit>=4.5.0",
    "pytest>=9.0.2",
    "pytest-mock>=3.15.1",
    "ruff>=0.14.6",
    "ty>=0.0.23",
]

[tool.pytest.ini_options]
pythonpath = ["extractor/src", "writer/src"]
testpaths = ["tests/extractor", "tests/writer", "tests/shared"]

[tool.ruff]
line-length = 120

[tool.ruff.lint]
extend-select = ["I", "UP"]

[tool.ty.environment]
extra-paths = ["extractor/src", "writer/src"]

[tool.uv]
package = false

[tool.uv.workspace]
members = ["packages/*"]

[tool.uv.sources]
shared = { workspace = true }
